### PR TITLE
PR to test fix

### PR DESCRIPTION
**Pull request by goldingn**

### CODE REVIEW

**Comment by goldingn** [comment]
looks like setting the environment variable in the matrix didn't override the CRAN environment variable, as I would expect it to: https://github.com/metacran/r-builder/blob/master/pkg-build.sh#L11

**Comment by goldingn** [comment]
Looks like I left some whitespace in the bash code, hopefully this will fix it

**Comment by goldingn** [comment]
I cna replicate this error on a CentOS (linux) machine, only when using the https CRAN mirror. In that case either the http or berkeley mirrors work fine.
I'm a it stumped as to why this PR doesn't fix it.

**Comment by timcdlucas** [comment]
Anything we can do to help? I'm really not at all up to date on any of this side of the package but happy to build and check locally or something.

**Comment by AugustT** [comment]
@goldingn This is an interesting bug!

I notice that the line you add to to .yml is not in the same format as the example you posted:

Example 'CRAN=${CRAN:-"http://cran.rstudio.com"}'
Yours `CRAN="http://cran.cnr.berkeley.edu/"`

Might this explain anything?

**Comment by goldingn** [comment]
Yeah, the line in R-builder means *if the CRAN variable isn't defined, set it to this* you can see that the specific repository does get used [here](https://travis-ci.org/zoonproject/zoon/jobs/120369518#L156) and [here](https://travis-ci.org/zoonproject/zoon/jobs/120369518#L522).

I think it must be something at either the CRAN end, or some change on Travis.

@timcdlucas I don't think there's anything to do. Have triggered them again and will google around a bit more for now

**Comment by AugustT** [comment]
There is something [here](http://blog.palindromicstudios.com/r-unable-to-access-index-for-repository/) about the trailing slash being important, but I dont know why this would only become an issue now

**Comment by goldingn** [comment]
Yup saw that, though we're providing the link to the repository, rather than the index file so I shouldn't imagine it would be the same issue. Note that master is failing without the slash (using the CRAN repository) too.

Will try removing the slash any to see if that helps.

**Comment by goldingn** [comment]
Hmm @AugustT I think you may be right about the trailing slash. install.packages doesn't add it when adding `/src/contrib`, and `curl`ing cran mirrors like that doesn't get the index.

The questions are then a) why has this suddenly stopped working, and b) can we hack our way around it for now?

**Comment by AugustT** [comment]
Could CRAN have changed something at their end with means that the absence of a slash is now an issue when it wasn't before. If is is the case then we can't be the only people having this issue!

**Comment by timcdlucas** [comment]
Just in case this is related, I can't seem to install packages from CRAN at the moment. About to try on a different machine.

**Comment by goldingn** [comment]
It had occurred to me, but this is occurring on the current release version as well as dev.

@timcdlucas which flavour  of Linux are you using?
Travis is Ubuntu Precise

**Comment by timcdlucas** [comment]
Think my problem is just that the Bristol mirror seems to be down. So probably not relevant to this especially if you're still setting the mirror to somewhere in USA.

@goldingn  I'm ubuntu Trusty (14).

**Comment by goldingn** [comment]
ah, you mean on the repositories, rather than the R version. Yes I agree, that seems likely

**Comment by AugustT** [comment]
I notice that r-builder is failing to build. Some sort of error with libcurl and https. This could have something to do with our issues? 

https://travis-ci.org/metacran/r-builder/builds/120624624#L5979

The last successful build of r-builder was 3 days ago which fits with our timeline. 

I have raised an issue on the r-builder github page. If we can figure out how to fix it in the meantime perhaps we can put in a PR to r-builder? https://github.com/metacran/r-builder/issues/46

**Comment by AugustT** [comment]
They suggest we move to using ['proper R travis'](http://blog.rstudio.org/2016/03/09/r-on-travis-ci/). @goldingn I thought we had gone down that road before, can't remember why we didn't stick with it, but it looks like they have been doing some dev work so it might be worth having another go.

**Comment by goldingn** [comment]
Well spotted. Yes, it seems to be something to do with libcurl. There was a closed issue on r-builder which threw a similar error on Windows. That was fixed by installing libcurl4-openssl-dev, which we're already doing.

Yes, a switch to Travis' native R support looks good. There was a reason it didn't work previously but hopefully it will now!

**Comment by AugustT** [comment]
move to r travis incoming https://github.com/zoonproject/zoon/pull/258

**Pull request closed without merging**
