### PR TITLE
Observation covariates

### PR DESCRIPTION
**Pull request by RTbecard**
Fixed cross validation bug in `zoonHelpers.R`

### CODE REVIEW

**Comment by AugustT** [comment]
@RTbecard Do you need any help here?

**Comment by RTbecard** [comment]
Ya sorry about this.  Was trying to figure out how to update my fork and didn't realize I was making the PR in the opposite direction!

**Comment by AugustT** [comment]
Haha! No problem. It would be good to incorporate any improvements you are making with the development repository so feel free to put in pull requests :)

**Comment by RTbecard** [comment]
Will do soon!  I've been going through the code I have some ideas on updating the workflow to include models I'm working with which use observation level-covariates (time, weather, etc.) for detection probability.  I should have something to share in a day or so!

**Pull request closed without merging**
