### PR TITLE
Modified to support simulated datasets and detection models

### PR DESCRIPTION
**Pull request by RTbecard**
- Added functions for manipulating dataframes without losing user defined attributes (`attributeFunctions.R`)
- Changed `zoonHelpers.R` to accept raster stacks with no layers (useful for simulated datasets where the data is generated in the process module) and allow user defined attributes in the `df` data.frame to be propagated through the workflow.

### CODE REVIEW

**Comment by AugustT** [comment]
Great stuff, I like the idea of new cbind definition, good shout.

Couple of comments:

You define your `cbind.zoon` function twice, I suggest you remove [this one](https://github.com/zoonproject/zoon/pull/334/commits/6ff410f1b261937b1208eab86e8c81aac9d7836a#diff-9dd63cc2d6a43b459b8929da40ddcc40R397)

It doesn't look like you have built the man pages for your new function but you have exported them.  Run the following to build all the documentation form the Roxygen tags you have added

```r
roxygen2::roxygenise()
# or ctrl+shift+D in rstudio
```

Travis - our annoying CI system who thinks he is sooo clever - [has an issue with your update](https://travis-ci.org/zoonproject/zoon/jobs/151241414#L904). I can replicate this error by installing this commit and running the failed test manually

```r
# install your PR
library(devtools)
install_github('zoonproject/zoon', ref = '6ff410f1b261937b1208eab86e8c81aac9d7836a')

#  test that fails
work1 <- workflow(occurrence = UKAnophelesPlumbeus,
                     covariate  = UKAir,
                     process    = Background(n=70),
                     model      = LogisticRegression,
                     output     = PrintMap)
Caught errors:
Error in ExtractAndCombData(x, covariate.output[[1]]): no slot of name "layers" for this object of class "RasterLayer"


Error: Stopping workflow due to error in process module.
 Workflow progress will be returned.
```

You may not be aware that the zoon package has a testing infrastructure. The tests run hundreds of lines of code testing that every element of the package produces the expected outcome, it is a great way to ensure that changes we make dont mess things up. To run the tests:

```r
test()
# or ctrl+shift+t in rstudio
```

Can you have a look at the error and see if you know why your edits have caused this problem. Let me know if you struggle and I can help out. Equally let me know if anything I have said here doesn't make sense

**Comment by RTbecard** [comment]
Sounds good, I wasn’t aware I could run the tests on my local machine!

I’ll address these right now and update the branch asap.

**Comment by RTbecard** [comment]
Alright, updated the branch and addressed the above errors and cleaned up the code... but I'm still failing the tests.  When I test locally, I get this:
```
Failed ---------------------------------------------------------------------------------------------------------------------------------------------------------------
1. Failure: ExtractAndCombData works. (@testExtractAndCombData.R#15) -------------------------------------------------------------------------------------------------
ExtractAndCombData(outOfExtentData, UKAirRas) did not throw an error.
```
In my branch when there's a empty raster passed to the `ExtractAndComData`, I allow the df to continue through the function.  From this error, I'm guessing the test is expecting an empty `ras` object to throw an error?

**Comment by AugustT** [comment]
That makes sense, let me dig into this today

**Comment by AugustT** [comment]
I have brought this PR down locally to my machine and I'm making a few changes:

I added a test of your new functionality to extractandcombine testing

```r
  # test that attributes are carried though
  attr(AplumbeusOcc, 'testing') <- list(1:5, 'test')
  y <- ExtractAndCombData(head(AplumbeusOcc), UKAirRas)
  expect_equal(list(1:5, 'test'), attr(y$df, 'testing'))
```

I added explicit testing for the other two functions you created

```r
# file testcbind.zoon.R
context('cbind.zoon')

test_that('cbind.zoon testing', {
  
  # create data.frames
  a <- data.frame(1:10, letters[1:10])
  attr(a, 'test') <- TRUE
  attr(a, 'test1') <- 1:3
  
  b <- data.frame(10:1, letters[10:1])
  
  # we expect cbind to drop the attributes
  expect_true(is.null(attr(cbind(a,b), 'test')))
  
  # we expect cbind.zoon to keep the attributes
  expect_equal(attr(cbind.zoon(a,b), 'test'), TRUE)
  expect_equal(attr(cbind.zoon(a,b), 'test1'), 1:3)
  
})
```

```r
# file testsubset.columns.zoon.R
context('subset.columns.zoon')

test_that('subset.columns.zoon testing', {
  
  # create data.frames
  a <- data.frame(1:10, letters = letters[1:10], 10:1)
  attr(a, 'test') <- TRUE
  attr(a, 'test1') <- 1:3
  
  # we expect subsetting to drop the attributes
  expect_true(is.null(attr(a[ ,c(1,2)], 'test')))
  
  # we expect subset.columns.zoon to keep the attributes
  expect_equal(attr(subset.columns.zoon(a, columns = c(1,3)), 'test'), TRUE)
  expect_equal(attr(subset.columns.zoon(a, columns = 'letters'), 'test1'), 1:3)
  
})
```

I modified the help file of the subset function to say you can use index too (doesn't have to be column names)

I changed the extract and combine behaviour so that it throws warnings rather than errors if the raster and occurence data dont match up.

```r
 # Check for rows in the occurrence data that have missing data
  NArows <- apply(occurrence[,c('longitude', 'latitude')],
                  1,
                  function(x) any(is.na(x)))
  
  if(any(NArows)){
    warning(sum(NArows), ' row(s) of occurrence data have NA values for latitude/longitude and will be removed')
    occurrence <- occurrence[!NArows, ]
  }
  
  # Check that all points are within the raster
  bad.coords <- is.na(cellFromXY(ras,
                                 occurrence[,c('longitude', 'latitude')]))
  if(any(bad.coords)){
    nr_before <- nrow(occurrence)
    occurrence <- occurrence[!bad.coords, ]
    nr_after <- nrow(occurrence)
    
    if(nr_after > 0){
      warning (paste(nr_before - nr_after,
                     'occurrence points are outside the raster extent and have been removed before modelling leaving',
                     nr_after, 'occurrence points'))
    } else if(nr_after == 0) {
      warning(paste('All occurrence points are outside the raster extent. Try changing your raster.'))
    }
  }
```

**Comment by AugustT** [comment]
@RTbecard I have added your changes + my changes to my fork of `zoon`. I have put in a pull request to your `PR` branch (more comments there).

**Comment by AugustT** [comment]
Just noticed another issue. Your new functions should be camel case to match our other functions, i.e. cbindZoon and subsetColumnsZoon. At present the package check gets angry as it thinks they are methods, which they aren't (this is because <method>.<class> is a special thing) I don't mind changing this later if you like.

**Comment by RTbecard** [comment]
ah, I just pulled the changes before seeing the last comment!  I can update this in the next hour with the new function names..

**Comment by AugustT** [comment]
Now that we have allowed empty rasters and occurrence datasets we should create a `NoRaster` and `NoOccurrence` module.

Don't worry, the method thing is only a warning so should still all pass and we can make that change after

**Comment by AugustT** [comment]
-0.009% hardly seems a failure!

**Pull request merged**
