### PR TITLE
CRAN release candidate 0.6.3

### PR DESCRIPTION
**Pull request by goldingn**
Don't merge until accepted on CRAN!

Implements @timcdlucas's user-prompted package installation in `GetPackage`, and fixes up a couple of new CRAN NOTEs

### CODE REVIEW

**Comment by AugustT** [comment]
This has now been accepted on CRAN

**Comment by AugustT** [comment]
Pull requests that have a failing status can’t be merged on a phone

Who knew?! @goldingn can you merge?

**Comment by goldingn** [comment]
I'm on phone now too :)

Will merge tomorrow unless someone else beats me to it.

**Comment by AugustT** [comment]
Sorry @timcdlucas, didn't think you had merge privelages else I would have asked you! Cheers.

**Comment by timcdlucas** [comment]
Phenomenal cosmic power, itty bitty living space.

**Pull request merged**
