### PR TITLE
Changed GetModuleList() to be subsettable by module type

### PR DESCRIPTION
**Pull request by Doi90**

### CODE REVIEW

**Comment by AugustT** [comment]
Good job, it looks to pass the travis tests but the test coverage has dropped. Do you want to write a test that covers the new functionality you added?

**Comment by AugustT** [comment]
You can see the red lines not covered in testing here: https://codecov.io/gh/zoonproject/zoon/pull/387/src/R/SearchFunctions.R

**Comment by Doi90** [comment]
Since I don't see codecov mentioned anywhere in the repository, I assume I have to modify this file?

https://github.com/zoonproject/zoon/blob/master/tests/testthat/testGetModuleList.R

**Comment by AugustT** [comment]
Yes that's right. That script runs the tests for the GetModuleList function. It uses the package 'testthat' to do it and the help files of that package will help you understand how it works. CodeCov is a service, like travis, that monitors a repository on GitHub. CodeCov looks at your tests and works out which lines of your code it is checking. A good coverage is over 90%, we fought hard to get there so I'm keen to keep it that way.

Let me know if you run into any problems.

**Comment by AugustT** [comment]
Good job, -0.03% I can live with ;) Thanks for taking the time to go the extra step

**Pull request merged**
