### PR TITLE
Vignette style updates. Spelling/grammar

### PR DESCRIPTION
**Pull request by Doi90**

### CODE REVIEW

**Comment by AugustT** [comment]
I see a number of failure on Travis:

**Comment by AugustT** [comment]
1. Failure: Expected errors (@testTransformCRS.R#39) 
  2. Error: occurrence data is handled as expected when CRSs vary (@testTransformCRS.R#94) 
  3. Failure: simple, package data workflow works. (@testWholeWorkflows.R#30) 
  4. Failure: Check basic quoted workflow. (@testWholeWorkflows.R#62) 
  5. Failure: chains work. (@testWholeWorkflows.R#337) 
  6. Failure: chains work. (@testWholeWorkflows.R#355) 
  7. Failure: chains work. (@testWholeWorkflows.R#373) 
  8. Failure: chains work. (@testWholeWorkflows.R#391) 
  9. Failure: chains work. (@testWholeWorkflows.R#409)

**Comment by goldingn** [comment]
Yeah, master is failing too, so it's probably not this PR. I'll try and fix this next week.

**Comment by Doi90** [comment]
I'll give it a once over tonight, but these are primarily text changes only so I cant imagine them failing tests. The only code chunk changes would have been adding some blank lines for readability

**Comment by goldingn** [comment]
OK, I can see why the tests are failing, but I'm having trouble understanding why it *ever passed*. 

My best guess is that something was up in one of the dependencies (testthat would be my best guess) at the time of the last PR.

I'll just fix the failing tests and open a PR

**Comment by goldingn** [comment]
Ah, so some of these were because I broke Background (a bit), which is relied on by zoon's tests

**Comment by AugustT** [comment]
I think I used background in a lot of the workflow tests

**Comment by AugustT** [comment]
I think it is important that the master branch is never failing. I don't get the emails about zoon failing, but happy to help out when it does. Sounds like @goldingn has it in hand this time.

**Comment by goldingn** [comment]
Bingo

**Pull request merged**
