### PR TITLE
Add citation to mee paper

### PR DESCRIPTION
**Pull request by timcdlucas**
Add paper citation.

Also add my orcid id. Others can use this as a template if they like.

### CODE REVIEW

**Comment by timcdlucas** [comment]
This is failing, but the nightlies are failing too. So unless I find time to fix whatever was broken before, I'll just leave this here for now.

**Comment by AugustT** [comment]
Now passing

**Comment by timcdlucas** [comment]
Great thanks. Did you manually restart the tests for this pr? I was wondering how to do it.

**Comment by AugustT** [comment]
Yeah I did. Just click on the link to view the failed build on Travis and once there click restart. Might need privileges?

**Comment by Doi90** [comment]
Pretty sure you need owner/maintainer privileges. Nick has to restart
Travis checks for our pull requests in the zoontutorials repo even though
we have the ability to merge them when passed.

**Pull request merged**
