### PR TITLE
testing updates - passes check()

### PR DESCRIPTION
**Pull request by AugustT**

### CODE REVIEW

**Comment by AugustT** [comment]
You suck Travis

**Comment by goldingn** [comment]
:)

**Comment by AugustT** [comment]
testModuleHelp, like the workflow tests that are failing for you, also accesses the web...

**Comment by goldingn** [comment]
Okey doke.

I suggest we wait to make sure my new travis set-up works, I'll merge it into the main repo, then you can merge it and add `skip_on_CRAN()` too all of those.

That way we *should* get two tests for each R version (current or devel), one with CRAN checks (and these tests turned off) and the other with non-CRAN checks (and running those tests)

**Comment by AugustT** [comment]
Okay, I will hold off.

Just so you know I only just located the detailed error messages in the Travis output for the ModuleHelp issue.

When the ModuleHelp tests fail the error is:

```
download.file(method = "libcurl") is not supported on this platform
```

**Comment by goldingn** [comment]
Huh. Well the R version will be different in the new Travis set up, so fingers crossed this will just go away. If not, we'll have to tweak the r installation

**Comment by goldingn** [comment]
OK, new Travis is set up so you should be able to incorporate these with `skip_on_cran()` calls. Fingers crossed that'll solve all of our problems!

**Comment by goldingn** [comment]
sorry, wrong PR...

**Pull request closed without merging**
