### PR TITLE
trying cleaner travis build with workaround for testthat bug

### PR DESCRIPTION
**Pull request by goldingn**
again, opening PR to test new set up on Travis

### CODE REVIEW

**Comment by goldingn** [comment]
sorry, pr to wrong repo

**Comment by AugustT** [comment]
I saw that the .yml file for spocc was very different to ours but I'm afraid I know little about travis. It also looks like the ModuleHelp tests I just wrote are failing, but they are fine on my machine, BALLZ

**Comment by goldingn** [comment]
Yup, I prefer the [metacran package builder](https://github.com/metacran/r-builder), but couldn't get it to work because of [this devtools bug](https://github.com/hadley/testthat/issues/86#issuecomment-143878211). There's a fix suggested there so trying that here (or rather [here](https://github.com/goldingn/zoon/pull/2)).

If this works it will run faster and test on R-devel as well as the previous version of R. We could probably also set up CRAN and non-CRAN checks (and we can skip awkward tests in the CRAN versions),

That's a big if, last time I tried for many hours and then gave up after polluting the commit history

**Comment by goldingn** [comment]
well whatdya know, it (almost) worked!

**Pull request closed without merging**
