### PR TITLE
implementing good practice guidelines

### LINKED ISSUE #349: check code for good practice
This package runs some handy check to comment on coding style and stability:
[https://github.com/MangoTheCat/goodpractice]()

It can be run with e.g.:

```r
source("https://install-github.me/MangoTheCat/goodpractice")
library(goodpractice)
gp('~/path/to/zoon')
```

On my fork it spots a couple of marginal issues, like: more than 80 characters per line;
[one line](https://github.com/zoonproject/zoon/blob/master/R/attributeFunctions.R#L32) using `F` instead of `FALSE`; use of e.g. `1:length(...)` instead of `seq_along()` in `DoModuleFunctions.R` and `print.zoonWorkflow.R`; assignment with `=` in `print.zoonWorkflow.R`. The test coverage seems to disagree with our Travis builds though...

When I get time, I'll run this on the main fork and put in a PR amending the low-hanging fruit.

### PR DESCRIPTION
**Pull request by goldingn**
To fix #349

### CODE REVIEW

**Comment by goldingn** [comment]
Still to do:

 - [ ] replace overlength lines in tests
 - [ ] replace all `sapply` statements with `vapply`

Debatable:
 - [ ] remove date from description
 - [ ] switch dependencies to imports
 - [ ] make `test_outputs` less complex

**Comment by AugustT** [comment]
How have I never used vapply?!

**Comment by goldingn** [comment]
(I'm still planning to get to this soon BTW)

**Comment by goldingn** [comment]
this is now merged with my master branch, for which I'll open a PR

**Pull request closed without merging**
