### PR TITLE
add function to generate the arguments to a module

### PR DESCRIPTION
**Pull request by smwindecker**
added a function called ModuleArguments, which takes the module name and returns to the console the function's arguments. It only returns those a user can define (so not including the zoon-specific . files).

### CODE REVIEW

**Comment by smwindecker** [comment]
will add test code.

**Comment by AugustT** [comment]
@smwindecker You evaluate the module in the global environment to then be able to get the formals. To avoid this function appearing in the users environment could you evaluate it in the local environment of the function or alternatively remove the function from the environment after you have got the formals? @goldingn can probably advise

**Comment by smwindecker** [comment]
Thanks @AugustT I'll revise.

**Comment by smwindecker** [comment]
did that do the trick?

**Comment by AugustT** [comment]
Looks good to me... In it goes :)

**Comment by AugustT** [comment]
Haha, closed before mergeing, whoops. Should be in the master version now

**Pull request merged**
