### PR TITLE
test updates and bug fixes

### PR DESCRIPTION
**Pull request by AugustT**

### CODE REVIEW

**Comment by goldingn** [comment]
failing on release but not devel - is this the same libcurl error?

**Comment by AugustT** [comment]
@goldingn libcurl use makes this fail on the as cran version, could we change the code to make this pass?

```
1. Error: GetModuleList renew --------------------------------------------------
url(method = "libcurl") is not supported on this platform
1: withCallingHandlers(eval(code, new_test_environment), error = capture_calls, message = function(c) invokeRestart("muffleMessage"), 
       warning = function(c) invokeRestart("muffleWarning"))
2: eval(code, new_test_environment)
3: eval(expr, envir, enclos)
4: GetModuleList(renew = TRUE) at testGetModuleList.R:6
5: readLines(url(canary_urls[i], method = "libcurl"))
6: url(canary_urls[i], method = "libcurl")
7: .handleSimpleError(function (e) 
   {
       e$calls <- head(sys.calls()[-seq_len(frame + 7)], -2)
       signalCondition(e)
   }, "url(method = \"libcurl\") is not supported on this platform", quote(url(canary_urls[i], 
       method = "libcurl")))

2. Error: GetModuleList no renew -----------------------------------------------
url(method = "libcurl") is not supported on this platform
1: withCallingHandlers(eval(code, new_test_environment), error = capture_calls, message = function(c) invokeRestart("muffleMessage"), 
       warning = function(c) invokeRestart("muffleWarning"))
2: eval(code, new_test_environment)
3: eval(expr, envir, enclos)
4: GetModuleList(renew = FALSE) at testGetModuleList.R:23
5: readLines(url(canary_urls[i], method = "libcurl"))
6: url(canary_urls[i], method = "libcurl")
7: .handleSimpleError(function (e) 
   {
       e$calls <- head(sys.calls()[-seq_len(frame + 7)], -2)
       signalCondition(e)
   }, "url(method = \"libcurl\") is not supported on this platform", quote(url(canary_urls[i], 
       method = "libcurl")))
```

**Comment by goldingn** [comment]
It's R-release (3.2.2) that fails, both with and without CRAN, no? https://travis-ci.org/zoonproject/zoon/builds/85084525

Either way, should be doable. I'll have a look

**Comment by AugustT** [comment]
Sorry, yes I miss read

**Comment by AugustT** [comment]
I thought that this libcurl stuff was in the current release?

**Comment by goldingn** [comment]
yup, it should be. Could be that the ubuntu 12.04 version Travis uses doesn't have it installed by default, or that r-builder installs from somewhere weird. Trying to replicate the environment on docker now.

**Comment by goldingn** [comment]
OK, looks like ubuntun 12.04 & thereofre Travis's image comes without curl, and R-builder only installs it for R-devel for some reason: https://github.com/metacran/r-builder/blob/master/pkg-build.sh#L113

So I've added explicit installation which I'm testing on your fork here: https://travis-ci.org/zoonproject/zoon/builds/85099424

**Comment by goldingn** [comment]
That works and I've merged *just the travis change* into the main repo so that you can merge into this PR

**Comment by AugustT** [comment]
Great stuff

**Comment by goldingn** [comment]
BTW you can set up Travis on your fork if that would be handy - just need to sign in with your github credentials and flick a switch!

**Comment by AugustT** [comment]
Yeah I was wondering how to do that... I'll  take a look

**Comment by goldingn** [comment]
looks like you didn't merge the new `.travis.yml`?

**Comment by AugustT** [comment]
DOH! Going to stop doing PRs to here until my fork build successfully to keep it cleaner

**Pull request closed without merging**
