### PR TITLE
Change inputs to output modules

### PR DESCRIPTION
**Pull request by timcdlucas**
Change workflow and internal functions so that output modules receive rasters from the process modules rather than from the covariate modules.

This means that the covariate data can be altered and used later.

So far this has been used in [MESSMask.R](https://github.com/timcdlucas/modules/blob/f88406eea308bd6fc32e79d19c6faffd4b0422e5/R/MESSMask.R).

But the same ideas would be needed for a PCA modules or a MaxEnt bootstrap variable importance module I think.

### CODE REVIEW

**Comment by timcdlucas** [comment]
Note, this does NOT change the arguments that output modules have. No code in the modules repo needs to change.

**Comment by timcdlucas** [comment]
@AugustT @goldingn  Does this just mean that I should be reducing the code test coverage?

I'll merge for now and bolster the test coverage tomorrow.

But also looking at the outputs, everything seems to have the same coverage and I haven't added any functions... oh well.

**Comment by AugustT** [comment]
The coverage is done line by line. Since the change is so small I wouldn't worry about it too much. Looking at the CodeCov output I can't really see where this new un-checked code comes from.

**Comment by timcdlucas** [comment]
Ok that's what I thought as well. I'll spend a bit of time maybe improving test coverage anyway. It's probably my turn to be a good unit-testing citizen...

**Comment by AugustT** [comment]
This changes requires an update to the IO definitions of output modules in Building_a_module.Rmd

**Comment by timcdlucas** [comment]
Oh yeah, I'll change that.

**Pull request merged**
